### ISSUE TITLE
Pull Latest Base Model - cds pull --from http://localhost:4004 -u bob (Not Working in VSCode - blank folder)

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/teched2022-AD264#7]
Hi there, 

Just trying to follow Step 3: https://github.com/SAP-samples/teched2022-AD264/wiki/3.-Custom-Extensions

Am using VS Code 1.73.1
with @sap/cds-dk v6.3.1

In Section **Pull Latest Base Model :**
when executing this command: **cds pull --from http://localhost:4004 -u bob**,
I'm getting a blank node_modules\@capire\incidents folder.

**Comment by sammok83** [comment]
As a workaround to continue with **cds pull** not working the exercise, I did the following:

Create an index.cds file in the incidents folder, with the following contents:

```javascript
namespace sap.capire.incmgt; //> important for reflection

using from './db/schema';
using from './srv/incidents-service';
using from './app/fiori';
```

do a cds compile (Compiles to CSN format) and copy the contents of that file to the _node_modules/@capire/incidents_ folder. Name that file as _index.csn_, and continue with the exercise.

The original issue remains a bug.

**Comment by renejeglinsky** [comment]
Hi Samuel,
this bug has been solved with the latest release. Could you please confirm and close this issue?

All the best,
René

**Comment by sammok83** [comment]
@renejeglinsky Still not working for me.
For reference, these are the npm packages installed:
```JSON  
"dependencies": {
    "@sap/cds": "6.5.0",
    "@sap/cds-mtxs": "^1.5.1",
    "express": "^4"
  },
```
